language: python

python:
  - "3.4"
  - "3.5"

branches:
  only:
    - master

before_install:
  - cd tests
  - pip install -r requirements.txt
  - cd ..

install:
  - python setup.py install

script:
  - cd tests
  - python manage.py test

after_success:
  coveralls