language: python

python:
  - "3.4"
  - "2.7"

branches:
  only:
    - master

before_install:
  - cd tests
  - pip install -r requirements.pip
  - cd ..

install:
  - python setup.py install

script:
  - cd tests
  - python manage.py test

after_success:
  coveralls